services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-task-rest-api
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/init-scripts:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
    driver: local
    name: task-rest-api-postgres-data